# Copyright 2021-2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

run:
  timeout: 10m
  build-tags:
    - e2e

linters:
  disable-all: true
  enable:
    - containedctx
    - contextcheck
    - depguard
    - errcheck
    - errchkjson
    - errname
    - gochecknoinits
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - ineffassign
    - importas
    - lll
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - stylecheck
    - tenv
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax # Allow everything unless explicitly denied below.
        deny:
          - pkg: k8s.io/kubernetes
            desc: "do not use k8s.io/kubernetes directly"
  errcheck:
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
  errchkjson:
    check-error-free-encoding: true
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/nutanix-cloud-native)
      - localmodule
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofumpt:
    extra-rules: true
  gomoddirectives:
    replace-allow-list:
      - github.com/nutanix-cloud-native/prism-go-client
  importas:
    no-unaliased: false
    alias:
      - pkg: "sigs.k8s.io/cluster-api/api/v1beta1"
        alias: clusterv1
  lll:
    line-length: 120
  stylecheck:
    # https://staticcheck.io/docs/configuration/options/#dot_import_whitelist
    dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega
  testifylint:
    enable-all: true

issues:
  exclude-rules:
    # ignore errcheck for flags.Parse (it is expected that we flag.ExitOnError)
    # ignore response.WriteError as it always returns the err it was passed
    - source: "flags.Parse|response.WriteError"
      linters:
        - errcheck
    - source: "//( \\+kubebuilder:|go:generate)"
      linters:
        - lll
