# Copyright 2024 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: pc-creds-for-ipam
stringData:
  credentials: |
    [
      {
        "type": "basic_auth",
        "data": {
          "prismCentral":{
            "username": "${NUTANIX_USER}",
            "password": "${NUTANIX_PASSWORD}"
          }
        }
      }
    ]
---
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: NutanixIPPool
metadata:
  name: nutanixippool-sample
spec:
  prismCentral:
    address: ${NUTANIX_ENDPOINT}
    port: 9440
    credentialsSecretRef:
      name: pc-creds-for-ipam
  subnet: ${NUTANIX_SUBNET_NAME}
  cluster: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
---
apiVersion: ipam.cluster.x-k8s.io/v1beta1
kind: IPAddressClaim
metadata:
  name: my-ip
spec:
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io
    kind: NutanixIPPool
    name: nutanixippool-sample
