# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This configuration is for teaching kustomize how to update name ref and var substitution
nameReference:
  - kind: Issuer
    group: cert-manager.io
    fieldSpecs:
    - kind: Certificate
      group: cert-manager.io
      path: spec/issuerRef/name
