# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    cluster.x-k8s.io/v1beta1: v1alpha1

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/
resources:
- bases/ipam.cluster.x-k8s.io_nutanixippools.yaml

patches:
- path: patches/cainjection_in_nutanixippools.yaml
- path: patches/enhancedvalidation_in_nutanixippools.json
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: nutanixippools.ipam.cluster.x-k8s.io
